Replace email tickets by a task
inventaire/inventaire-client pull request #252
Opened 2020-12-30 19:05 UTC by jum-s

2021-01-23 15:37 UTC, maxlath requested changes

2021-01-23 15:37 UTC, maxlath commented on app/api/tasks.js
> +  deduplicateWork: action('deduplicate-work'),
update required after https://github.com/inventaire/inventaire/commit/b2a18f9
```suggestion
  deduplicateWorks: action('deduplicate-works'),
```

2021-01-23 15:42 UTC, maxlath commented on app/modules/tasks/views/current_task.js
> +    if (this.model.get('type') === 'deduplicate') {
```suggestion
    if (this.model.get('entitiesType') === 'humans') {
```

2021-01-23 17:22 UTC, jum-s commented on app/api/tasks.js
> +  deduplicateWork: action('deduplicate-work'),
reviews are precious :)

2021-01-26 09:29 UTC, maxlath approved these changes

2021-03-01 11:35 UTC, merged