add a fedeversable setting checkbox
inventaire/inventaire-client pull request #290
Opened 2021-09-08 10:15 UTC by jum-s

now that [`activity-pub`](https://github.com/inventaire/inventaire/pull/538) server branch is merged, allow user to become fediversable

2021-09-19 14:27 UTC, maxlath commented
the `input { appearance: auto; }` makes that checkbox appear as a vertical bar:
![b](https://user-images.githubusercontent.com/1596934/133931184-0be2b79b-79c3-4f65-82b8-6a570e8de4f6.png)
Removing that rule here and in `app/lib/components/notification_toggler.svelte` doesn't seem to break in Chrome, contrary to what the comment says: can we remove those rules?
Also, a11y point, those checkbox labels are too small, what about adding `label{ font-size: 1rem }` here and in `app/lib/components/notification_toggler.svelte`?

2021-09-19 14:28 UTC, maxlath requested changes
the `input { appearance: auto; }` makes that checkbox appear as a vertical bar:
![b](https://user-images.githubusercontent.com/1596934/133931184-0be2b79b-79c3-4f65-82b8-6a570e8de4f6.png)
Removing that rule here and in `app/lib/components/notification_toggler.svelte` doesn't seem to break in Chrome, contrary to what the comment says: can we remove those rules?
Also, a11y point, those checkbox labels are too small, what about adding `label{ font-size: 1rem }` here and in `app/lib/components/notification_toggler.svelte`?

2021-09-20 09:04 UTC, jum-s commented
done in `e925328f`

2021-09-20 15:49 UTC, maxlath approved these changes

2021-09-20 15:50 UTC, merged