Recover email validation request
inventaire/inventaire-client pull request #307
Opened 2022-01-07 16:37 UTC by maxlath

It use to be possible to request a new email with a token to validation the user email address; that was lost when the settings got rewritten in Svelte, and this PR brings that back

2022-01-10 08:18 UTC, jum-s requested changes
this is graphically getting a lot of user's attention, but its neither an error nor even a problem, only optional button if one havent received an email.

Instead i would integrate it the same way as other points in the settings
Title: "unverified email"
Message: in warning color with the current icon
Action button: like any other

on the blocking points:
-    align text on the left (as every text of the whole settings)
-    keep action button to a regular color, this black is not very spread (i would wait to refactor modals with svelte to introduce new action colors)
-    no background color for this section (same as any other section in settings)

2022-01-10 12:00 UTC, maxlath commented
@jum-s style harmonization done in 8f548eb

2022-01-10 15:07 UTC, jum-s commented on app/modules/settings/components/email_validation.svelte
> +  <button class="button light-blue radius" on:click={emailConfirmationRequest}>
```suggestion
  <button class="light-blue-button radius" on:click={emailConfirmationRequest}>
```

2022-01-11 11:14 UTC, maxlath commented on app/modules/settings/components/email_validation.svelte
> +  <button class="button light-blue radius" on:click={emailConfirmationRequest}>
done in 59c863a

2022-02-07 10:03 UTC, jum-s approved these changes

2022-02-07 16:41 UTC, merged